import { Category, Product, StoreConfig, User } from '@/types/domain'
type Source=Record<string,unknown>
const value=(source:Source,...keys:string[])=>keys.map(key=>source[key]).find(item=>item!==undefined)
const text=(source:Source,...keys:string[])=>String(value(source,...keys)??'')
const number=(source:Source,...keys:string[])=>Number(value(source,...keys)??0)
const bool=(source:Source,...keys:string[])=>Boolean(value(source,...keys))
const list=<T>(source:Source,...keys:string[])=>(value(source,...keys)??[]) as T[]

// Este archivo es el único lugar que debe conocer nombres alternativos del backoffice.
// Ajustar los aliases cuando se reciba su contrato definitivo.
export const backofficeAdapter={
 product(source:Source):Product{return{id:text(source,'id','product_id'),slug:text(source,'slug'),name:text(source,'name','nombre'),shortDescription:text(source,'shortDescription','short_description','descripcion_corta'),description:text(source,'description','descripcion'),imageUrl:text(source,'imageUrl','image_url','imagen_principal'),gallery:list<string>(source,'gallery','galeria'),price:number(source,'price','precio'),promotionalPrice:value(source,'promotionalPrice','promotional_price','precio_promocional')===undefined?undefined:number(source,'promotionalPrice','promotional_price','precio_promocional'),currency:'ARS',categoryId:text(source,'categoryId','category_id','categoria_id'),ingredients:list<string>(source,'ingredients','ingredientes'),dietaryTags:list<Product['dietaryTags'][number]>(source,'dietaryTags','dietary_tags','etiquetas'),available:bool(source,'available','disponible'),stock:number(source,'stock','stock_disponible'),availableDays:list<Product['availableDays'][number]>(source,'availableDays','available_days','dias_disponibles'),availableDate:text(source,'availableDate','available_date','fecha_disponibilidad')||undefined,orderDeadline:text(source,'orderDeadline','order_deadline','horario_limite'),active:bool(source,'active','activo'),featured:bool(source,'featured','destacado'),bestSeller:bool(source,'bestSeller','best_seller','mas_vendido'),displayOrder:number(source,'displayOrder','display_order','orden'),createdAt:text(source,'createdAt','created_at')||new Date().toISOString(),badge:text(source,'badge')||undefined}},
 category(source:Source):Category{return{id:text(source,'id','category_id'),name:text(source,'name','nombre'),slug:text(source,'slug'),description:text(source,'description','descripcion')||undefined,sortOrder:number(source,'sortOrder','sort_order','orden'),active:bool(source,'active','activo')}},
 user(source:Source):User{return{id:text(source,'id','user_id'),firstName:text(source,'firstName','first_name','nombre'),lastName:text(source,'lastName','last_name','apellido'),email:text(source,'email','correo'),phone:text(source,'phone','telefono'),addresses:list<User['addresses'][number]>(source,'addresses','direcciones'),createdAt:text(source,'createdAt','created_at')}},
 storeConfig(source:Source):StoreConfig{return{id:text(source,'id'),name:text(source,'name','nombre'),tagline:text(source,'tagline','slogan'),currency:'ARS',locale:text(source,'locale')||'es-AR',timezone:text(source,'timezone')||'America/Argentina/Buenos_Aires',orderDeadline:text(source,'orderDeadline','order_deadline'),phone:text(source,'phone','telefono'),email:text(source,'email','correo'),pickupEnabled:bool(source,'pickupEnabled','pickup_enabled'),deliveryEnabled:bool(source,'deliveryEnabled','delivery_enabled'),minimumOrder:number(source,'minimumOrder','minimum_order'),address:text(source,'address','direccion'),businessHours:text(source,'businessHours','business_hours'),socialLinks:list<StoreConfig['socialLinks'][number]>(source,'socialLinks','social_links','redes'),banners:list<StoreConfig['banners'][number]>(source,'banners')}},
 list<T>(payload:unknown,mapper:(source:Source)=>T):T[]{const data=Array.isArray(payload)?payload:(payload&&typeof payload==='object'&&'items'in payload?(payload as {items:unknown[]}).items:[]);return data.map(item=>mapper(item as Source))},
}
