'use client'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/contexts/AuthContext'
import { useCart } from '@/contexts/CartContext'
import { useNotification } from '@/contexts/NotificationContext'
import { orderService, productService } from '@/services'
import { Order } from '@/types/domain'
export default function OrderQuickActions(){const{session}=useAuth(),cart=useCart(),{notify}=useNotification(),router=useRouter(),[orders,setOrders]=useState<Order[]>([]),[working,setWorking]=useState('');useEffect(()=>{if(session)orderService.getByUser(session.user.id).then(result=>setOrders(result.data))},[session]);if(!session||!orders.length)return null;const repeat=async(order:Order)=>{setWorking(order.id);const omitted:string[]=[];for(const line of order.details){try{const product=(await productService.getById(line.productId)).data;if(!product.available||!product.stock){omitted.push(product.name);continue}cart.add(product,Math.min(line.quantity,product.stock))}catch{omitted.push(line.productName)}}setWorking('');notify(omitted.length?`Se actualizaron precios y se omitieron: ${omitted.join(', ')}.`:'Pedido agregado con precios y stock actualizados.',omitted.length?'info':'success');router.push('/carrito')};const cancel=async(order:Order)=>{if(!window.confirm(`¿Confirmás cancelar el pedido ${order.id}?`))return;setWorking(order.id);try{const updated=(await orderService.cancel(order.id)).data;setOrders(current=>current.map(item=>item.id===updated.id?updated:item));notify(`Pedido ${order.id} cancelado.`,'info')}catch(cause){notify(cause instanceof Error?cause.message:'No se pudo cancelar.','error')}finally{setWorking('')}};return <section className="mx-auto max-w-7xl px-5 pb-12 lg:px-8"><h2 className="font-display text-2xl text-forest">Acciones rápidas</h2><p className="mt-1 text-xs text-ink/50">Al repetir, usamos precios y disponibilidad actuales.</p><div className="mt-4 flex gap-3 overflow-x-auto pb-2">{orders.slice(0,4).map(order=><article key={order.id} className="min-w-64 rounded-2xl bg-white p-4"><b className="text-sm text-forest">{order.id}</b><p className="text-xs text-ink/50">{order.details.length} productos · {order.status}</p><div className="mt-3 flex gap-2"><button disabled={!!working} onClick={()=>repeat(order)} className="rounded-full bg-orange px-3 py-2 text-[10px] font-bold text-white disabled:opacity-40">Repetir</button>{['pending','confirmed'].includes(order.status)&&<button disabled={!!working} onClick={()=>cancel(order)} className="rounded-full border border-red-200 px-3 py-2 text-[10px] font-bold text-red-700 disabled:opacity-40">Cancelar</button>}</div></article>)}</div></section>}
